intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
import intf_libs += component-core-intf%lib{component-core-intf}
import intf_libs += assets%lib{assets}
import intf_libs += geometry%lib{geometry}
import intf_libs += stones%lib{stones}
import intf_libs += procgen-core%lib{procgen-core}
import intf_libs += transactions%lib{transactions}

lib{kbuild-temp}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
hxx{version}: in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
}

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DKBUILD_TEMP_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DKBUILD_TEMP_SHARED_BUILD

# Export options.
#
lib{kbuild-temp}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{kbuild-temp}: cxx.export.poptions += -DKBUILD_TEMP_STATIC
libs{kbuild-temp}: cxx.export.poptions += -DKBUILD_TEMP_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{kbuild-temp}: bin.lib.version = "-$version.project_id"
else
  lib{kbuild-temp}: bin.lib.version = "-$version.major.$version.minor"

# Install into the kbuild-temp/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/kbuild-temp/
  install.subdirs = true
}
